name: ROS2 CI
on: push

jobs:
  ros2_ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.14
      with:
        required-ros-distributions: eloquent
    - name: Source ROS environment
      run: "source /opt/ros/eloquent/setup.bash && env && ros2 --help"
    - run: vcs --help
    - name: Check if colcon exists after setup
      run: colcon info; bash -c colcon info
    - uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: telegram_ros2
        vcs-repo-file-url: .travis.rosinstall
