name: Test telegram_ros2
on: push

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: telegram_ros2
